// Generated by https://quicktype.io

import { User } from "./user.interface";

export interface LoginResponse {
    user:  User;
    token: string;
}

export interface RegisterResponse {
    user: User,
    token: string
}


